name: "HCL AppScan CodeSweep"
on:
  [push]
  #pull_request:
    #types: [opened,synchronize]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/ApplicationInspector-Action@v1
      - uses: actions/upload-artifact@v3
        with:
            name: AppInspectorResults
            path: AppInspectorResults.json
    env: 
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
